[package]
name = "h11"
version = "0.1.0"
authors = ["Tynor Fujimoto <tynorf@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bytes = "0.4.12"
failure = "0.1.6"
http = "0.1.19"
httparse = "1.3.4"
